## Programa2.Estandarizacion

![Texto Alternativo](logoitqv1.jpg)

* Nombre: Martin Sosa
* Fecha:  **24-09-2026**
* Repositorio: <a href="https://github.com/Martin122334/machine2026nocturno">Link del repositorio de Github</a>

![Texto Alternativo](python_logo.png)

In [7]:
from sklearn import preprocessing
import numpy as np

In [8]:
# Carga de datos.
X_train = np.array([[ 1., -1., 2.],
[ 2., 0., 0.],
[ 0., 1., -1.]])

In [9]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()
# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [11]:
X_train_2 = np.array([[ 1., -1., 2.],
[ 2., 0., 0.],
[ 0., 1., -1.]])

In [13]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [16]:
# Comprobar si las matrices estandarizadas son iguales
print(np.array_equiv(X_train_std, X_train_2_std))

True
